In [3]:
import tensorflow as tf
import datetime
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [4]:
model=load_model('model.h5')
with open('label_encode_gender.pkl','rb') as file:
    label_gender = pickle.load(file)
with open('label_onehot_encoder_geo.pkl','rb') as file:
    label_geo=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [19]:
input_data={
'CreditScore':600,
'Geography':'France',
'Gender':"Male",
'Age':40,
'Tenure':3,
'Balance':6000,
'NumOfProducts':2,
'HasCrCard':1,
'IsActiveMember':1,
'EstimatedSalary':50000
            
}

In [20]:
input_data=pd.DataFrame([input_data])

In [21]:
geoEncoded=label_geo.transform(input_data[['Geography']]).toarray()

In [22]:
df_geoEncoded=pd.DataFrame(geoEncoded,columns=label_geo.get_feature_names_out(['Geography']))

In [23]:
genderEncoded=label_gender.transform(input_data[['Gender']])

c:\ML\DL-ANN\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [24]:
input_data=pd.concat([input_data.drop(['Geography'],axis=1), df_geoEncoded],axis=1)

In [25]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,6000,2,1,1,50000,1.0,0.0,0.0

In [26]:
input_data['Gender']=genderEncoded

In [27]:
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,6000,2,1,1,50000,1.0,0.0,0.0

In [28]:
input_data_scalled=scaler.transform(input_data)
input_data_scalled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -1.12240462,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [30]:
#predict the person leaves the bank or %notebook
get_pred=model.predict(input_data_scalled)
get_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step

array([[0.01520315]], dtype=float32)

In [33]:
get_pr=get_pred[0][0]

get_pr

np.False_

In [34]:
if get_pr>0.5:
    print("The person will leave the bank")
else:
    print("The person will not leave the bank")

The person will not leave the bank

In [4]:
import pandas as pd

In [24]:
df9=pd.DataFrame({'CreditScore':[600,700,800],
     'Geography':['France','Spain','Germany']})
df10=pd.DataFrame({'CreditScore':[600,700,800],
      'Graph':['Fra','hello','Germany']})

In [13]:
df9

   CreditScore Geography
0          600    France
1          700     Spain
2          800   Germany

In [16]:
df10

   CreditScore    Graph
0          600      Fra
1          700    hello
2          800  Germany

In [25]:
missing_cols=df9.columns.difference(df10.columns)

In [26]:
missing_cols

Index(['Geography'], dtype='str')

In [27]:
for col in missing_cols:
    df10[col]=0
    print(df10)

   CreditScore    Graph  Geography
0          600      Fra          0
1          700    hello          0
2          800  Germany          0